version: "3"

services: 
  app:
    build: ./app
    ports: 
      - "3000:3000"
    env_file: ./app/.env

  ms_mensageiro:
    build: ./ms_mensageiro
    env_file: ./ms_mensageiro/.env

  ms_autentica:
    build: ./ms_autentica
    env_file: ./ms_autentica/.env

  ms_email:
    build: ./ms_email
    env_file: ./ms_email/.env

